library(raster)

setwd("/home/uff/Downloads")
df <- read.csv("updated_file_escolas.csv", h=T, sep=",")
head(df)
coordinates(df) <- c("Longitude", "Latitude")
shapefile(df,"shapes_escolas/total.shp", overwrite=TRUE)
dir.create("shapes_escolas")
shapefile(df[df$POLO == 1,],"shapes_escolas/polo1.shp")
shapefile(df[df$POLO == 2,],"shapes_escolas/polo2.shp")
shapefile(df[df$POLO == 3,],"shapes_escolas/polo3.shp")
shapefile(df[df$POLO == 4,],"shapes_escolas/polo4.shp")
shapefile(df[df$POLO == 5,],"shapes_escolas/polo5.shp")
shapefile(df[df$POLO == 6,],"shapes_escolas/polo6.shp")
shapefile(df[df$POLO == 7,],"shapes_escolas/polo7.shp")